server:
  port: 9527
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.110.47:8848
      # ${spring.application.name}-${spring.profile.active}.${spring.cloud.nacos.config.file-extension}
      config:
        server-addr: 120.26.110.47:8848 #Nacos服务配置中心地址
        file-extension: yaml #指定yaml格式的配置
  application:
    name: short-link-gateway
  config:
    import: nacos:short-link-gateway-dev.yaml


