server:
  port: 8002
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 634f4e71-ba53-4d2b-9b47-2023e2032c14
      # ${spring.application.name}-${spring.profile.active}.${spring.cloud.nacos.config.file-extension}
      config:
        server-addr: 127.0.0.1:8848 #Nacos服务配置中心地址
        file-extension: yaml #指定yaml格式的配置
  application:
    name: short-link-project
  config:
    import: nacos:short-link-project-dev.yaml
short-link:
  stats:
    locale:
      amap-key: 5b3345018d85c0fbc07283099b269bc1
  domain:
    default: csj.com
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
